### ISSUE TITLE
Error al arrancar el microservicio

### ISSUE THREAD

**Issue by isaioliva** [marcelomunozr/sneakers-city-spring-boot#2]
@marcelomunozr 
mvn spring-boot:run
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.seneakers:springbootapp >---------------------
[INFO] Building springbootapp 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.5.1:run (default-cli) > test-compile @ springbootapp >>>
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ springbootapp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ springbootapp ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to c:\testEVO\Marcelo\sneakers-city-spring-boot\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.843 s
[INFO] Finished at: 2021-06-28T10:09:19-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project springbootapp: Fatal error compiling: invalid target release: 11 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by marcelomunozr** [comment]
@isaioliva 
lo más probable que esté tratando compilar proyecto java 11 en un ambiente con java 8.

se agrega plugin con posible solución al document:
 _pom.xml_
 
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <source>1.8</source>
        <target>1.8</target>
    </configuration>
</plugin>
```
